---
title: "CMPE2150 Lab 07"
subtitle: "Stepper Control"
author: "Taylor, Moore, and Armstrong"
date: last-modified
date-format: "DD MMM YYYY"
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    fontcolor: "#005cb9"
    grid: 
      margin-width: 350px
  pdf:
    papersize: letter
    geometry: 
      - top=30mm
      - bottom=30mm
      - left=25mm
      - right=70mm
      - marginparwidth=50mm
      - heightrounded
    include-in-header: 
      text: |
        \usepackage{lastpage}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhead[L]{CMPE2150 Lab 07}
        \fancyhead[R]{Stepper Control}
        \fancyfoot[C]{\thepage/\pageref*{LastPage}}
  gfm:
      preview-mode: normal
toc: true
toc-location: right
toc-expand: true
reference-location: margin
citation-location: margin
cap-location: margin
fig-cap-location: margin
css: content.css
editor: visual
title-block-banner: "#002d74"
---

In this laboratory exercise, you will focus on two of the modes of operation you saw in action in the test code provided for the associated Self Assessment: Full Stepping and Half Stepping.

Write a program that does the following:

1.  The five pushbuttons on the microcontroller board with have the following functions:
    -   Single presses of the middle switch will select between Full Stepping and Half Stepping.
    -   The left switch will switch to reverse; the right switch will switch to forward.
    -   The top switch will switch to high speed; the bottom switch will switch to low speed.
2.  For "Low Speed", the controller will advance through the step sequences at $0.25 s$ per sequence so the pattern can be observed on the Stepper controller board's LEDs -- four sequences per second.
3.  For "High Speed", the controller will advance through the step sequences at $2.5 ms$ per sequence, resulting in a single rotation time of about $5 s$ for Full Stepping and about $10 s$ for Half Stepping.

Use the same port pins on the microcontroller board as were used in the associated Self Assessment, and use the microcontroller board's $+5 V$ rail to power the Stepper motor.

Put a piece of tape or other "flag" on the output shaft so the rotation of the shaft can be clearly observed.

Ask your instructor to grade your functional system out of five marks. Record the grade assigned below. \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Submit your "main.c" code here for an additional five marks. Make sure you document your work (i.e. comments required!). You are encouraged to use your existing HC9S12 libraries from your micro course, and to extend them to support motor control.
