---
title: "CMPE2150 PCB Project C"
subtitle: "PCB Layout"
author: "AJ Armstrong"
date: last-modified
date-format: "DD MMM YYYY"
bibliography: references.bib
biblio-style: ieee
csl: ieee.csl
format:
  html:
    embed-resources: true
    smooth-scroll: true
    fontcolor: "#005cb9"
    grid:
      margin-width: 350px
  pdf:
    papersize: letter
    geometry:
      - top=30mm
      - bottom=30mm
      - left=15mm
      - right=80mm
      - marginparwidth=60mm
      - marginparsep=10mm
      - heightrounded
    include-in-header:
      text: |
        \usepackage{lastpage}
        \usepackage{fancyhdr}
        \usepackage{titling}
        \pagestyle{fancy}
        \fancyhead[L]{CMPE2150 PCB Project C}
        \fancyhead[R]{PCB Layout}
        \fancyfoot[C]{\thepage/\pageref*{LastPage}}
        \setlength{\droptitle}{-2cm}
toc: true
toc-location: right
toc-expand: true
reference-location: margin
citation-location: margin
cap-location: margin
fig-align: default
fig-cap-location: margin
footnotes-hover: true
css: content.css
editor: visual
title-block-banner: "#002d74"
fig-env: "figure"
keep-tex: true
---

::: callout-tip
I'm going to stop reminding you to increment version numbers, check in and push at major milestones, because you already do that reflexively.
:::

### PCB Layout

Now that we have a fully annotated and checked schematic, we can begin the process of layout out a PCB. This process will follow the procedure in the tutorial rather closely, so most of the tasks should be reasonably familiar. This is always true, but particularly in PCB layout it is important to be neat, to check things carefully and to pay attention to constraints and instructions. Very subtle errors on a PCB design can make the boards useless after manufacture and waste hundreds of dollars and weeks of time on even a small test run. Your instructors will rarely have time to do more than a cursory check of this work, but you are encouraged to review each others' work and offer feedback and suggestions, up to the normal limits of not sharing designs.

### Part 1 - Setting Up the Board

Open your project's PCB editor and:

-   Select *File → Page Settings* and set the page up the same way we did for the schematic in Part A.

-   Change the default units from `mm` to `mils` by selecting the *mil* button on the left toolbar. Mils[^1] are far more commonly used in North America.

-   On the top menu bar, change the grid spacing to `20 mils`.

[^1]: Thousandths of an inch

Now, go to *File → Board Setup...* and make or confirm the following settings:

-   *Board Stackup → Physical Stackup:* Leave as 2 copper layers, as this is still a relatively simple board.

-   *Text & Graphics → Defaults:* Change *Units* to `mils` then round the default properties at the top up to the nearest mil.

-   *Design Rules → Design Constraints:* Round constraint values up to the nearest whole mil.

-   *Design Rules → Net Classes:* Round constraint values up to the nearest whole mil.

-   You may leave the remaining settings at default values.

### Part 2 - Component Placement

First, some general comments on technique and expectations:

-   We'll place all the components first, without doing any of the traces (wires). However, as you place components note that the 'rat's nest' lines show what will need to connect to what. Paying attention to that and rotating and placing parts to avoid having the rats nest lines cross over will simplify adding the traces. Of course, you can't always avoid it in a PCB layout just as you can't in a schematic. Keeping it to a minimum is, however, very helpful.

-   If you have a well-designed schematic, it can be an excellent guide to your layout. Follow similar principles (signals go left to right, power at the top, ground at the bottom) unless you have a good reason not to.

-   Components should be oriented (and parallel) with either the left or top edge.

-   Parts should be oriented the same and lined up where possible. Make sure labels are configured so you can read them without having to rotate the board over much.

-   Do this in a couple of passes. First just place components in a general area, adjacent to what they need to be adjacent to, and as uncluttered as possible, with a neat rat's nest. In subsequent passes, neaten it up, rotate things as necessary and align.

-   Do not place components inside each others' courtyard (see the F.Courtyard and R.Courtyard layers). These indicate minimum spacing for a part away from other parts.

-   Silk screen labels should be neat and not overlap. You may move them and rotate them as needed, but it should always be clear which part they refer to.

-   Remember that you can simplify your working field by hiding and showing layers as you work.

-   If you need to move things around to make space, remember that you can select multiple components and move them as a group.

Now we will place the components from our schematic:

-   Import the schematic: *Tools → Update PCB from schematic…*: If you get an error about the green LED, try removing the appended colour from the symbol name. Place the big bundle of symbols to one side of the entire document, not on your actual PCB page.

    -   Confirm against the schematic that you have footprints for all of the parts you expect. If not, go back to the schematic and confirm that you selected a (correct) footprint. I actually had some trouble getting the barrel jack to show up, which I resolved by deleting the part in the schematic and replacing it, then re-updated the PCB from the schematic.
    -   Check that your footprints are all correct. In particular, that those parts that are supposed to be through-hole are through-hole and those that are surface-mount are surface mount. If the footprint is incorrect, you can just correct it on the schematic and re-update. This happened to me, in that for some reason I had the default through-hole footprint for the PNP transistors.

    ::: callout-caution
    It is important that you confirm the presence of all of your components and that they have the correct footprints before you start placing them. If you're halfway through your layout when you discover a missing component or incorrect footprint, and then have to update from the schematic again, it can invalidate some of your work and force you to move things around.
    :::

-   Begin placing components with the power supply elements (barrel jack, VR, electrolytic caps, diodes, switch and polyfuse).

    -   The barrel jack will actually stick slightly out past the edge of your board when we establish where that is, so place it at the far left of your placement area.
    -   The switch should be near the barrel jack and oriented so that sliding it toward the top of the board will be the *on* position.
    -   The LED (power indicator) should be adjacent to the switch so that when the switch is turned on, it slides toward the LED.
    -   The two electrolytic caps should be adjacent to the VR.
    -   Do not crowd the VR. It gets hot, and might want a heat sink. Orient it so that it the back tab is toward the edge of the board.

-   Now place the resistors, except for the potentiometer. Again, don't worry about rotation and exact location as much as a neat arrangement near things that will be interconnected.

-   Place the transistors near their biasing resistors, rearranging as needed to make room.

-   Place $C_3$ near its transistor.

-   Place the comparator ($U_{2A}$). You may find it useful to move $R_9$ to $R_{11}$ to one side of the comparator.

-   Place the potentiometer and the header pins adjacent to the edge of the design.

-   Now, rotate parts—if needed—to help untangle the rats nest. If you do so, adjust the labels to be consistent with the unrotated parts. It is helpful to do this while zoomed in. It is inevitable that you will have a few crossed ratsnest lines, but you want to reduce them as much as possible. One trick I sometimes use after rotation is to swap the silk screen for the component name (e.g. $R8$) and its value ($2.2k$) by selecting the two of them (but not the rest of the part), right-clicking and selecting `Swap` to make it match the orientation of other components.

-   Take some time to neaten and align the parts into a rectangular shape. When ordering a board, the size of the PCB is a significant component of the cost, so you want the smallest possible area. But don't go overboard—you'll still need some space to move things around as you work. You can always reduce the size later.

-   Finally, place your edge cuts to neatly contain your design. Ensure the barrel jack, VR, potentiometer and header row are next to edges.

### Part 3 - Power Plane Copper Pours

At this point you certainly do not need me to remind you to regularly save and check-in your work, especially at important milestones in the process, so I won't do so.

Add a ground plane copper zone to the bottom (`B.Cu`) copper layer of the board, encompassing the whole board:

-   It should attach to the `GND` net.

-   Use a hatch pattern fill. You can accept the defaults for the remainder.

-   Fill all zones to see the effect of this.

Now, note that all the through-hole connections to the `GND` net have little spokes indicating they are connected (eg, the two electrolytic caps have connections to that net). We no longer have to route those, which is convenient. You also now have the option of pushing a via from the top top layer surface mount to get to ground on the bottom layer. When you zoom into the board, you should see that pads are labelled with the net the connect to, so you can identify the ones that would like to be connected to the `GND` net on the bottom.

Because we are using surface mount parts, much of our routing will be on the top layer, but you always have the option of using a via (or the pad of a through-hole component, which exists on both sides of the board). You can even route on the bottom layer, and the copper layer will automatically be adjusted away from your traces. Be wary, though! Your traces can disconnect regions of the copper pour (creating *islands* that are disconnected from the net).

Use the *Show only zone boundaries* button on the left tool bar to hide the details of the ground plane. Note that the ground pins on your components no longer show a ratsnest line, because they are now connected.

All right, now do exactly the same thing on the top (`F.Cu`) layer of the board, but this time for the `VCC` net.

With luck, your routing problem just got substantially easier. Remember to regularly refill the zones ($B$) and make them visible again to make sure things haven't gone awry.

### Part 4 - Routing Traces

We'll now start routing the connections between components. For the most part this should be fairly straightforward. Please observe the following rules and guidelines:

-   Do most of the routing on the top surface, only using a via to change layers when necessary to handle crossing a trace or to avoid breaking one of your power planes into islands. I usually route everything that doesn't require changing layers first.xxx

-   Do not connect traces together at mid-points. Only connect at a pad.

-   Do not make right-angle turns. Always do two $45^\circ$ turns. This prevents undercutting the trace in manufacture.

-   Make traces neat. Run them in parallel at consistent distances apart and avoid complex routes. The shorter and more direct the better. Prefer vertical and horizontal to angled.

-   You may need to move or rotate parts, but try to avoid it if possible. Such changes often cascade into lots of other changes.

-   Start with the any surface-mount `GND` pads (like on $R_1$) and use a via to quickly connect them to the ground plane on the bottom.

Keep going until you have replace the whole rats nest with valid traces.

### Submission

When you have completed all the above—including having no DRC errors or warnings—and checked and reviewed your work, ask your instructor to review your design with you. Make any changes they require. When you are done submit the PCB design.
