---
title: "CMPE2150 SA 05"
subtitle: "Relay and SSR Circuits"
author: "Taylor, Moore, and Armstrong"
date: last-modified
date-format: "DD MMM YYYY"
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    fontcolor: "#005cb9"
    grid: 
      margin-width: 350px
  pdf:
    papersize: letter
    geometry: 
      - top=30mm
      - bottom=30mm
      - left=25mm
      - right=70mm
      - marginparwidth=50mm
      - heightrounded
    include-in-header: 
      text: |
        \usepackage{lastpage}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhead[L]{CMPE2150 SA 05}
        \fancyhead[R]{Relay and SSR Circuits}
        \fancyfoot[C]{\thepage/\pageref*{LastPage}}
toc: true
toc-location: right
toc-expand: true
reference-location: margin
citation-location: margin
cap-location: margin
fig-cap-location: margin
css: content.css
editor: visual
title-block-banner: "#002d74"
---

### Omron G2R-2-DC12

The first set of questions in this assessment are based upon your knowledge of transistor-controlled relay circuits and information provided in the manufacturer's datasheet for the relay in your kit, the [Omron G2R-2-DC12](https://omronfs.omron.com/en_US/ecb/products/pdf/en-g2r.pdf).

Note that this datasheet covers a number of devices, so you need to make sure you're accessing the correct part number when accessing the specifications.

  1. Dielectric strength refers to \_\_\_\_\_\_\_\_\_\_
      a. the strength of a dielectric material, expressed as a function of aging due to repetitive arcing between terminal contacts.
      b. the maximum voltage that may be applied across the terminals of a relay while they are open.
      c. the maximum voltage that may be applied between the coil and the contacts before a resulting electric current will flow between them.
      d. a measure of the capacitance of the polarizing electrostatic field that develops between switch contacts while they are open.
  
  2. What is the basic dielectric rating of the G2R-2-DC12 relay, in volts? \_\_\_\_\_\_\_\_\_\_

  3. The G2R-2-DC12 relay in your kit has a fully-sealed enclosure. \_\_\_\_\_\_\_\_\_\_ (True or False)

  4. What type of protection does the enclosure of the G2R-2-DC12 relay provide? \_\_\_\_\_\_\_\_\_\_
      a. prevents ingress of solder flux during soldering
      b. prevents damage due to corrosive atmospheric gases
      c. prevents protection from electromagnetic field flux
      d. prevents influx of cleaning solvent during immersion cleaning

  5. How many circuits can the G2R-2-DC12 control simultaneously? \_\_\_\_\_\_\_\_\_\_

  6. For the G2R-2-DC12 relay, how many circuit elements can each relay switch be connected to? \_\_\_\_\_\_\_\_\_\_

  7. Which statement describes the operation of the contacts in the G2R-2-DC12 relay?
      a. all contacts are normally open
      b. all contacts are normally closed
      c. each switch has a normally-open contact and a normally-closed contact

  8. What is the nominal coil voltage for the G2R-2-DC12 relay? \_\_\_\_\_\_\_\_\_\_

  9. For the G2R-2-DC12 relay, what type of power should be supplied to the relay coil? \_\_\_\_\_\_\_\_\_\_ (AC or DC)

  10. For the G2R-2-DC12 relay, once the relay is activated, what can the voltage be reduced to without the relay releasing, in volts? \_\_\_\_\_\_\_\_\_\_

  11. What is the coil current rating of the G2R-2-DC12 relay, in milliamps? \_\_\_\_\_\_\_\_\_\_

  12. What is the rated coil resistance of the G2R-2-DC12 relay? \_\_\_\_\_\_\_\_\_\_

  13. The specified coil voltage and current accurately reflect the expected coil resistance for the G2R-2-DC12 relay. \_\_\_\_\_\_\_\_\_\_ (True or False)

  14. If a 2N3904 is used to activate the 2GR-2-DC12 relay, in microamps, the Base current must be greater than \_\_\_\_\_\_\_\_\_\_ ${\mu}A$.
{{< pagebreak >}}
  15. If a ZVN2110A FET transistor is used to activate the coil of a G2R-2-DC12 relay \_\_\_\_\_\_\_\_\_\_:
      a. a diode should be placed, reverse biased, across the coil
      b. a series resistor should be installed at the Gate
      c. a pull-down resistor should be installed at the circuit input
      d. all of the above

  16. If a ZVN2110A FET is used to activate a G2R-2-DC12 relay, the series Gate resistor should be designed to handle the coil current.\_\_\_\_\_\_\_\_\_\_ (True or False)

  17. What is the rated current-carrying capacity for the contacts of the G2R-2-DC12, in amps, with a resistive load? \_\_\_\_\_\_\_\_\_\_

  18. From the performance graphs for the G2R-2-DC12, what is the current handling capacity of the contacts, in milliamps, for a resistive load, if the supply voltage is $100 V_{DC}$? \_\_\_\_\_\_\_\_\_\_

  19. If a G2R-2-DC12 relay is used to switch a 120 V circuit, the transistor used should be rated to over 120 V. _\_\_\_\_\_\_\_\_\_ (True or False)

  20. The G2R-2-DC12 can be used as a switch for both DC and AC circuits. _\_\_\_\_\_\_\_\_\_ (True or False)

### PR3BMF41NSKF Solid-State Relay

The second set of questions concerns the [PR3BMF51NSLH Solid-State Relay](https://media.digikey.com/pdf/Data%20Sheets/Sharp%20PDFs/PR3BMF51NSKF.pdf) in your kit.

  1. How many pins are present on the PR3BMF41NSKF? \_\_\_\_\_\_\_\_\_\_

  2. The PR3BMF41NSKF SSR can be used to control \_\_\_\_\_\_\_\_\_\_:
      a. DC circuits only
      b. AC circuits only
      c. both DC and AC circuits

  3. For the PR3BMF41NSKF SSR, what test current, in milliamps, was used to determine the Input Forward Voltage? \_\_\_\_\_\_\_\_\_\_

  4. For the PR3BMF41NSKF, what is the Input Forward voltage, typically? \_\_\_\_\_\_\_\_\_\_

  5. For the PR3BMF41NSKF SSR, if five-volt logic is being used to activate the input, what would be a suitable 10% standard resistor to put in series with the LED? \_\_\_\_\_\_\_\_\_\_

  6. When using a transistor to activate the PR3BMF41NSKF SSR, you must protect the transistor with a reverse-biased diode.  _\_\_\_\_\_\_\_\_\_ (True or False)


  7. For the PR3BMF41NSKF SSR, what is the maximum recommended Load Supply Voltage? \_\_\_\_\_\_\_\_\_\_

  8. For the PR3BMF41NSKF SSR, which pins would you use in the load circuit? \_\_\_\_\_\_\_\_\_\_:
      a. 1 and 2
      b. 2 and 3
      c. 5 and 6
      d. 5 and 8
      e. 6 and 8

  9. For the PR3BMF41NSKF SSR, what is the Absolute Maximum continuous ON-state current, in amps? \_\_\_\_\_\_\_\_\_\_

  10. For the PR3BMF41NSKF SSR, at a temperature of 100$^\circ$C with no heat sink, what is the maximum continuous ON-state current limit, in milliamps? \_\_\_\_\_\_\_\_\_\_

::: content-hidden
{{< pagebreak >}}

::: border
### Answers
#### Omron G2R-2-DC12
 1. the maximum voltage that may be applied between the coil and the contacts before a resulting electric current will flow between them.
 2. $5000 V$
 3. False
 4. prevents ingress of solder flux during soldering
 5. 2
 6. 2
 7. each switch has a normally-open contact and a normally-closed contact
 8. $12 V$
 9. DC
 10. $1.8 V$
 11. $43.6 mA$
 12. $275 \Omega$
 13. True
 14. $436 {\mu}A$
 15. All of the above
 16. False
 17. $5 A$
 18. $350 mA$
 19. False
 20. True
### PR3BMF41NSKF Solid-State Relay
 1. 7
 2. AC circuits only
 3. $20 mA$
 4. $1.2 V$
 5. $180 \Omega$
 6. False
 7. $240 V$
 8. 6 and 8
 9. $1.2 A$
 10. $220 mA$


:::
:::
