---
title: "CMPE27000 Syllabus"
subtitle: "Communications and Networking"
author: "AJ Armstrong"
date: last-modified
date-format: "DD MMM YYYY"
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    fontcolor: "#005cb9"
    grid: 
      margin-width: 350px
  pdf:
    papersize: letter
    geometry: 
      - right=50mm
   # include-in-header: 
    #  text: |
     #   \usepackage{scrlayer-scrpage}
     #   \rohead(Header)
     #   \lofoot(Footer)
reference-location: margin
citation-location: margin
css: syllabus.css
editor: visual
title-block-banner: "#002d74"
---

## Instructors

+------------+--------------+--------------------------------+----------------------------------------------------+--------------+
| Semester   | Sections     | Instructor                     | Contact                                            | Office Hours |
+============+==============+================================+====================================================+==============+
| Fall 2026  | A01, A02     | AJ Armstrong                   | [aja\@nait.ca](mailto://aja@nait.ca "aja@nait.ca") | TBA          |
+------------+--------------+--------------------------------+----------------------------------------------------+--------------+

## Instruction

This is a course introducing basic data communications and building up through some basic industrial communication protocols. It is designed to give you the foundation to describe, select, and implement basic data communication protocols between devices as well as describe modern embedded device communication on wired and wireless networks.

Much of your work will be self-driven. While your instructor will introduce topics and new theory, you will be expected to do reading and research, testing your understanding with self-assessment exercises. Most class time will be spent working on the practical exercise, with your instructor assisting you in practicing, developing, and assessing your skills.

\newpage

## Evaluation

As it is a course focusing on practical skills, evaluation in CMPE2700 will be via practical exercises (Labs and Projects) which will typically have a design component followed by implementation or simulation of a design with measurement and testing of the finished product.

Marks will be assigned according to the following category weightings. Unless otherwise specified, assignments in a given category will have equal weight.

+-------------------------------+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| Category                      | Weight             | Notes                                                                                                                                                   |
+===============================+====================+=========================================================================================================================================================+
| Assignments                   | 10%                | Generally performed on the student's own time at the beginning of each topic. Typically marked automatically.                                           |
+-------------------------------+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| Laboratory Exercises (Labs)   | 40%                | One per topic. Checked-off in class by your instructor.                                                                                                 |
+-------------------------------+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projects                      | 50%                | One per major unit. Checked off in-class by your instructor on a scheduled day. **NB: You must complete all projects successfully to pass the course.** |
+-------------------------------+--------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------+

## Equipment

As this is a terminal hardware course, we may use elements from nearly all of the kits that you have purchased for the program. In particular, you will be expected to have all of the following, which are available in the NAIT bookstore. You should already have most of them from your first year studies. Items labelled "Home" do not need to be brought to the lab, but you may do so:

+----------------------------------------------------+-------------------------------------------------+
|                                                    |                                                 |
+====================================================+=================================================+
| - ETC Component Kit                                | - CNT Year 2 Kit                                |
+----------------------------------------------------+-------------------------------------------------+
| - CNT Year 1 Kit                                   | - Approved Multimeter (Home)                    |
+----------------------------------------------------+-------------------------------------------------+
| - CNT Electronics Bench Equipment Kit (Home)       | - Dual Breadboard                               |
+----------------------------------------------------+-------------------------------------------------+
| - CNT Electronics DC Power Kit (Home)              | - CSA-Rated Safety Glasses                      |
+----------------------------------------------------+-------------------------------------------------+
| - **STM32G031K8 Nucleo**                           | - Approved Calculator                           |
+----------------------------------------------------+-------------------------------------------------+

## Schedule

The following schedule is proposed. As always, this will be subject to change to fit operational realities. Changes to the schedule will be announced in class and on course channels as soon as known.

+--------+---------------------------------------------------+--------------------------------------------+
| Week   | Topic                                             | Assignments/Notes                          |
+========+===================================================+============================================+
| 1      | Course Introduction                               | *Lose one day to Late Start*               |
+--------+---------------------------------------------------+--------------------------------------------+
| 2      | Layer One Protocols                               | *Lose one day to Labour Day*               |
|        |                                                   |                                            |
|        |                                                   | A01: Layer 1                               |
+--------+---------------------------------------------------+--------------------------------------------+
| 3      | RS-232                                            | L01: RS-232 Loopback                       |
|        |                                                   |                                            |
|        |                                                   | A02: R2-232                                |
|        |                                                   |                                            |
|        |                                                   | L02: Differential Signalling               |
+--------+---------------------------------------------------+--------------------------------------------+
| 4      | RS-485                                            | A03: RS-485                                |
|        |                                                   |                                            |
|        |                                                   | L03: RS-485                                |
+--------+---------------------------------------------------+--------------------------------------------+
| 5      | Guided Transmission Media                         | A04: Guided Transmission Media             |
|        |                                                   |                                            |
|        |                                                   | L04: Twisted-Pair Termination and Testing  |
+--------+---------------------------------------------------+--------------------------------------------+
| 6      | Copper Media Limitations                          | **P01: RS-232 Communications**             |
|        |                                                   |                                            |
|        |                                                   | L05: Signal Characteristics and Filtering  |
+--------+---------------------------------------------------+--------------------------------------------+
| 7      | Intro to DGH Modules                              | *Lose one day to Thanksgiving*             |
|        |                                                   |                                            |
|        |                                                   | A06: The DGH Module                        |
+--------+---------------------------------------------------+--------------------------------------------+
| 8      | DGH Modules                                       | **P02: RS-485 Communications**             |
|        |                                                   |                                            |
|        |                                                   | L06: DGH Exploration                       |
+--------+---------------------------------------------------+--------------------------------------------+
| 9      | Unguided Transmission Media                       | A07: Unguided Transmission Media           |
|        |                                                   |                                            |
|        |                                                   | A08: Modulation and Demodulation           |
|        |                                                   |                                            |
|        |                                                   | L07: OOK, ASK, PSK, FSK                    |
+--------+---------------------------------------------------+--------------------------------------------+
| 10     | Broadband Signalling, Spread Spectrum             | **P03: Wireless Data Communication**       |
|        |                                                   |                                            |
|        |                                                   | A09: Broadband Signalling, Spread Spectrum |
+--------+---------------------------------------------------+--------------------------------------------+
| 11     | Industrial Protocols and TCP/IP                   | *Lose one day to Fall Break*               |
|        |                                                   |                                            |
|        |                                                   | A10: Industrial Protocols and TCP/IP       |
+--------+---------------------------------------------------+--------------------------------------------+
| 12     | Industrial Protocols and TCP/IP                   | **P04: Wireshark**                         |
+--------+---------------------------------------------------+--------------------------------------------+
| 13     | Modbus                                            | L08: Modbus                                |
+--------+---------------------------------------------------+--------------------------------------------+
| 14     | MQTT, IOT, IIOT                                   | L09: MQTT                                  |
+--------+---------------------------------------------------+--------------------------------------------+
| 15     | MQTT, IOT, IIOT                                   | **P05: MQTT**                              |
+--------+---------------------------------------------------+--------------------------------------------+
| 16     |                                                   | *Lose one day to Term End*                 |
+--------+---------------------------------------------------+--------------------------------------------+

## Policies

- Labs are no longer available for credit after the due date for the following Lab unless an extension is given by the instructor.

- Projects that are completed after the due date will receive a marks penalty of 20% per class period late unless an extension is given by the instructor.

- Safety glasses must be worn at all times in the Lab if anyone is using bench equipment.

- Promptness and preparation lead to success. Attendance will be monitored.
